### ISSUE TITLE
Missing prefix for the function get_moodle_version_major()

### ISSUE THREAD

**Issue by mudrd8mz** [blindsidenetworks/moodle-atto_recordrtc#10]
The function `get_moodle_version_major()` is defined in the plugin's lib.php and as such should have the `atto_recordrtc_` prefix like all others in that file.

**Comment by mudrd8mz** [comment]
By the way, there is `$CFG->branch` that you can maybe use of instead of manually checking against version number.

**Comment by jfederico** [comment]
We messed up here. It is actually not necessary as we are making the comparision against the version tag not the release tag.

See https://github.com/blindsidenetworks/moodle-atto_recordrtc/blob/master/lib.php#L39

That was updated in commit 8d0693e2f6acbe8dd629d05b4b5eb90f546d236a already in master
