### ISSUE TITLE
Why does it have own uploads.php?

### ISSUE THREAD

**Issue by mudrd8mz** [blindsidenetworks/moodle-atto_recordrtc#8]
It is not clear to me why there is a custom script uploads.php for serving the uploaded files. Why does not it use the standard file serving route via pluginfile.php?

**Comment by jfederico** [comment]
Good point. It was the first approach and it stayed that way.
There are another two issues regarding to the security of the files uploaded that Gavin raised after running a first test.
Both will definitely be addressed asap.

**Comment by mudrd8mz** [comment]
> There are another two issues regarding to the security of the files uploaded that Gavin raised

Were those published somewhere?

**Comment by mudrd8mz** [comment]
Nice, thanks :-)
