### ISSUE TITLE
Sanitize input in save.php

### ISSUE THREAD

**Issue by mudrd8mz** [blindsidenetworks/moodle-atto_recordrtc#9]
The save.php uses direct access to superglobal `$_POST` and passes the values directly to `create_file_from_pathname()` method. I know that the filename is cleaned inside that method. Yet it is generally discouraged to blindly trust the input like this.

I would recommend to switch over to `required_param()` or `optional_param()` with proper `PARAM_FILE` type declared, or at least perform the `clean_param()` manually before passing the value further. If nothing else than to prevent eventual security problems in the future when this code is refactored or copy & pasted elsewhere.

**Comment by jfederico** [comment]
This issue was fixed for 1.0-b2, but save.php was removed for 1.0-b3 as the way to store the files was changed
